name: cyberpay_mobile_2
description: A   Flutter project for cyberpay_mobile_2 .
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  connectivity_plus: ^3.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  currency_text_input_formatter: ^2.1.8
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  dropdown_search: ^5.0.5
  encrypt: ^5.0.1
  equatable: ^2.0.5
  file_picker: ^5.2.4
  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  firebase_storage: ^10.3.11
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^7.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  local_auth: ^2.1.3
  local_session_timeout: ^2.2.0
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  pdf: ^3.8.4
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  qr_code_scanner: ^1.0.1
  retrofit: ^3.3.1
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.1.1
  riverpod_annotation: ^1.1.1
  sembast: ^3.3.1+1
  sembast_web: ^2.0.1+1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  webview_flutter: ^4.0.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran-VariableFont_wght.ttf
        - asset: fonts/Catamaran-Regular.ttf
        - asset: fonts/Catamaran-Black.ttf
        - asset: fonts/Catamaran-ExtraBold.ttf
        - asset: fonts/Catamaran-ExtraLight.ttf
        - asset: fonts/Catamaran-Light.ttf
        - asset: fonts/Catamaran-Medium.ttf
        - asset: fonts/Catamaran-SemiBold.ttf
        - asset: fonts/Catamaran-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
